config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/question/search', to: 'search#index'
  get '/home/dashboard', to: 'dashboard#index'
  get '/notifications', to: 'notification#index'

  resources :questions, only: [:show, :create] do 
    resources :answers, only: [:create]
  end

  # Students routes
	  get '/students/sign_up', to: 'students#get_sign_up'
	  get '/students/sign_in', to: 'students#get_sign_in'
  	post '/students/sign_up', to: 'students#post_sign_up'
  	post '/students/sign_in', to: 'students#post_sign_in'
    delete '/students/sign_out', to: 'students#sign_out'

  # Teachers routes
	  get '/teachers/sign_up', to: 'teachers#get_sign_up'
	  get '/teachers/sign_in', to: 'teachers#get_sign_in'
	  post '/teachers/sign_up', to: 'teachers#post_sign_up'
	  post '/teachers/sign_in', to: 'teachers#post_sign_in'
    delete '/teachers/sign_out', to: 'teachers#sign_out'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  validates :title, presence: { message: "Title can't be blank" }
  validates :body, presence: { message: "Body can't be blank" }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_all!

  # def index
  #   if session[:student_user_id]
  #     @questions = Question.where(branch: session[:student_branch])
  #   else session[:teacher_user_id]
  #     @questions = Question.where(branch: session[:teacher_branch])
  #   end
  # end

  def show
    begin
      if session[:student_user_id]
        @question = Question.find(params[:id])
        if @question.branch == session[:student_branch]
          @question.increment!(:view_count, 1)
          return @question
        else
          flash[:alert] = "This question does not belongs to your branch"
          redirect_to home_dashboard_path and return
        end
      else
        @question = Question.find(params[:id])
        if @question.branch == session[:teacher_branch]
          @question.increment!(:view_count, 1)
          return @question
        else
          flash[:alert] = "This question does not belongs to your branch"
          redirect_to home_dashboard_path and return
        end
      end
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The Question does not exists"
      redirect_to home_dashboard_path and return
    end
  end

  # def new
  #   if session[:student_user_id]
  #     @question = Question.new
  #   else
  #     flash[:alert] = "Only students can ask questions"
  #     redirect_to questions_path and return
  #   end
  # end

  def create
    if session[:student_user_id]
      @question = Question.new(new_question_params)
      @question.lab_id = session[:student_user_id]
      @question.name = session[:student_name]
      @question.branch = session[:student_branch]
      @question.student_year = session[:student_year]
      if @question.save

        TeacherRecord.where(branch: session[:student_branch]).map do |teacher|
          teacher.teacher_notifications.create(body: "A new question has been posted, Title: \"#{new_question_params[:title]}\". Please check the recently added questions and answer the question.")
        end

        flash[:notice] = "Question has been succesfully added"
        redirect_to question_path(@question) and return
      end
    else
      flash[:alert] = "Only students can ask questions"
      redirect_to home_dashboard_path and return
    end
  end

  # def edit
  #   begin
  #     if session[:student_user_id]
  #       @question = Question.find(params[:id])
  #       if @question.branch == session[:student_branch]
  #         if @question.lab_id == session[:student_user_id]
  #           return @question
  #         else
  #           flash[:alert] = "Not authorized to edit this question"
  #           redirect_to questions_path and return
  #         end
  #       else
  #         flash[:alert] = "This question does not belongs to your branch"
  #         redirect_to questions_path and return
  #       end
  #     else
  #       flash[:alert] = "Only students can edit questions"
  #       redirect_to questions_path and return
  #     end
  #   rescue ActiveRecord::RecordNotFound
  #     flash[:alert] = "The Question does not exists"
  #     redirect_to questions_path and return
  #   end
  # end

  # def update
  #   begin
  #     if session[:student_user_id]
  #       @question = Question.find(params[:id])
  #       if @question.branch == session[:student_branch]
  #         if @question.lab_id == session[:student_user_id]
  #           if @question.update(edit_question_params)
  #             flash[:notice] = "Question updated"
  #             redirect_to question_path(@question) and return
  #           end
  #         else
  #           flash[:alert] = "Not authorized to update this question"
  #           redirect_to question_path(@question) and return
  #         end
  #       else
  #         flash[:alert] = "This question does not belongs to your branch"
  #         redirect_to questions_path and return
  #       end
  #     else
  #       flash[:alert] = "Only students can edit questions"
  #       redirect_to questions_path and return
  #     end
  #   rescue ActiveRecord::RecordNotFound
  #     flash[:alert] = "The Question does not exists"
  #     redirect_to questions_path and return
  #   end
  # end

  # def destroy
  #   begin
  #     if session[:student_user_id]
  #       @question = Question.find(params[:id])
  #       if @question.branch == session[:student_branch]
  #         if @question.lab_id == session[:student_user_id]
  #           if @question.delete
  #             flash[:notice] = "Question has been deleted succesfully"
  #             redirect_to questions_path and return
  #           end
  #         else
  #           flash[:alert] = "Not authorized to update this question"
  #           redirect_to question_path(@question) and return
  #         end
  #       else
  #         flash[:alert] = "This question does not belongs to your branch"
  #         redirect_to questions_path and return  
  #       end
  #     else
  #       flash[:alert] = "Only students can delete questions"
  #       redirect_to questions_path and return
  #     end
  #   rescue ActiveRecord::RecordNotFound
  #     flash[:alert] = "The Question does not exists"
  #     redirect_to questions_path and return
  #   end
  # end

protected

  def new_question_params
    params.require(:new_question).permit(:title, :body)
  end

  # def edit_question_params
  #   params.require(:edit_question).permit(:title, :body)
  # end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<%= form_for(@question, as: :edit_question, url: question_path(@question)) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  	<br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  	<br>
  <%= f.submit "Update Question" %>
<% end %>

app/views/questions/index.html.erb
<% if @questions.any? %>
	<% @questions.each do |question| %>
		<%= question.title %>
		<br>
		<%= question.body %>
		<br>
		<%= link_to "Show Question", question_path(question) %>
		<br>
		<%= link_to "Edit Question", edit_question_path(question) %>
		<br>
		<%= link_to "Delete Question", question_path(question), :method => :delete, data: { confirm: "Are you sure you want to delete this question?" } %>
	<% end %>
<% else %>
	No questions yet
<% end %>

app/views/questions/new.html.erb
<%= form_for(@question, as: :new_question, url: questions_path(@question)) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  	<br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  	<br>
  <%= f.submit "Add Question" %>
<% end %>

app/views/questions/show.html.erb
  <br><br>
  <!-- QUESTION CONTAINER STARTED -->
  <div class="container">
    
    <h3 style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
      Question</h3>
    <div class="card mb-3 rounded shadow-sm alert-danger" style="   border-bottom: 5px solid #d9534f ;">
      <div class="card-title">
        <div class="card-body">
          <p class="media-body" style="font-size: 25px;">
            <!-- put question title here -->
            <strong class="d-block text-dark"><i class="text-white bg-dark">Question Title:</i>  <strong class="text-dark" style="font-size: 19px;"><%= @question.title %> <strong style="font-size: 14px;" class="text-dark"><i> ~ (Posted by: <%= @question.name %>, <%= @question.branch.upcase %>, Year: <%= @question.student_year %>) - <%= time_ago_in_words(@question.created_at) %> ago</i></strong></strong></strong>
          </p>
          <div class="media text-muted pt-0">
            <p class="media-body pb-0">
              <!-- put question body  -->
              <strong class="d-block text-dark" style="font-size: 25px;"><i class="text-white bg-dark">Question Body:</i>  <strong class="text-dark" style="font-size: 19px;"><%= @question.body %></strong></strong>

              
            </p>
          </div>
        </div>
        <div class="card-footer alert-danger  border-0"> <!-- CARD FOOTER WITH VIEW COUNT AND ADD ANS BTN -->
          <div class="row align-items-end">
            <div class="col">
              <div class="text-left ">
                <small>Views: <span><%= @question.view_count %></span></small>
              </div>
            </div>
            
            <div class="col ">
              <div class="text-right ">
                <button type="button" class="btn btn-primary p-1 " data-toggle="modal" data-target="#examplemodalCenter">
                  Add Answer
                </button>
              </div>

                <!-- add ans  modal started-->
                <%= form_for(@answer = Answer.new, as: :new_answer, :class => "text-dark", url: question_answers_path(@question, @answer)) do |f| %>
                <div class="modal fade" id="examplemodalCenter" tabindex="-1" role="dialog"
                  aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title text-dark" id="exampleModalLongTitle">Answer</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                          <div class="form-group">

                            <%= f.label :short_answer, "Short Answer", html: { :for => "exampleInputEmail1" } %>
                            <%= f.text_field :short_answer, :class => "form-control", html: { :id => "exampleInputEmail1"} %>

                          </div>

                          <div class="form-group">
                            <%= f.label :descriptive_answer, "Descriptive Answer", html: { :for => "exampleFormControlTextarea1" } %>
                            <%= f.text_area :descriptive_answer, :class => "form-control", html: { :id => "exampleFormControlTextarea1", :rows => "3" } %>
                          </div>

                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <%= f.submit "Add Answer", :class => "btn btn-primary" %>
                      </div>
                    </div>
                  </div>
                 </div>
                 <% end %>


              </div>
            </div>
          </div><!-- CARD FOOTER WITH VIEW COUNT AND ADD ANS BTN -->


        </div>
      </div>
    </div>
  </div><!-- QUESTION CONTAINER ENDED --><br>

    <hr style="width: 80%;">

  <!-- ANSWERS CONTAINER STARTED -->
  <div class="container">
    <h3
      style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
      Answers</h3>
      <!-- OUTER CARD WITH GREEN BORDER STARTED -->
    <div class="card mb-3 rounded shadow-sm bg-light " style="border-width: 2px; border-color:#5cb85c ;">

      <div class="card-title text-dark ">
        <div class="card-body ">
        <% if @question.answers.any? %>
          <% @question.answers.each do |answer| %>
              <!-- INNER  CARD WITH GREEN BG STARTED-->
              <div class="card mb-3 rounded shadow-sm alert-success " style=" border-left: 5px solid #5cb85c ;">
                <div class="card-title text-dark ">
                  <div class="card-body  " >
                    <p class="media-body">
                      <!-- put Short Ans here -->
                      <strong class="d-block text-dark" style="font-size: 25px;"><i class="text-white bg-dark">Short Answer:</i>  <strong class="text-dark" style="font-size: 19px;"><%= answer.short_answer %> <strong style="font-size: 14px;" class="text-dark"><i> ~ (Posted by: <%= answer.name %>) - <%= time_ago_in_words(answer.created_at) %> ago</i></strong></strong></strong>
                    </p>
                    <div class="media text-muted pt-0">
                      <p class="media-body pb-0   ">
                        <!-- put Descriptive Ans here -->
                        <strong class="d-block text-dark" style="font-size: 25px;"><i class="text-white bg-dark">Descriptive Answer:</i>  <strong class="text-dark" style="font-size: 19px;"><%= answer.descriptive_answer %></strong></strong>
                      </p>
                    </div>
                  </div>
                </div>
              </div> <!-- INNER  CARD WITH GREEN BG ENDED-->
            <% end %>
          <% else %>
            <p><strong class="text-dark">Sorry, no one has posted any answer for this question yet.</strong></p>
          <% end %>


        </div>


      </div>
    </div><!-- OUTER CARD WITH GREEN BORDER  ENDED-->
  </div><!-- ANSWERS CONTAINER ENDED -->
  <br>
  <br>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>