config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/question/search', to: 'search#index'
  get '/home/dashboard', to: 'dashboard#index'
  get '/notifications', to: 'notification#index'

  resources :questions, only: [:show, :create] do 
    resources :answers, only: [:create]
  end

  # Students routes
	  get '/students/sign_up', to: 'students#get_sign_up'
	  get '/students/sign_in', to: 'students#get_sign_in'
  	post '/students/sign_up', to: 'students#post_sign_up'
  	post '/students/sign_in', to: 'students#post_sign_in'
    delete '/students/sign_out', to: 'students#sign_out'

  # Teachers routes
	  get '/teachers/sign_up', to: 'teachers#get_sign_up'
	  get '/teachers/sign_in', to: 'teachers#get_sign_in'
	  post '/teachers/sign_up', to: 'teachers#post_sign_up'
	  post '/teachers/sign_in', to: 'teachers#post_sign_in'
    delete '/teachers/sign_out', to: 'teachers#sign_out'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_all!
  
  def index
    if session[:student_user_id]
	  	if params[:search]
	  	  @results = Question.where("title LIKE ?", "%#{params[:search]}%").where(branch: session[:student_branch])
	  	else
	  	  flash[:alert] = "No search keyword entered"
	  	  redirect_to home_dashboard_path and return
	  	end
  	elsif session[:teacher_user_id]
 	  	if params[:search]
	  	  @results = Question.where("title LIKE ?", "%#{params[:search]}%").where(branch: session[:teacher_branch])
	  	else
	  	  flash[:alert] = "No search keyword entered"
	  	  redirect_to home_dashboard_path and return
	  	end
  	end	
  end

protected

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<br> <br>
<div class="container">
    <h3
      style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;">
     Search Result</h3>
      <!-- OUTER CARD WITH GREEN BORDER STARTED -->
    <div class="card mb-3 rounded shadow-sm bg-light " style="border-width: 2px; border-color:#5c96b8 ;">

      <div class="card-title text-dark ">
        <div class="card-body ">
          <!-- INNER  CARD WITH GREEN BG STARTED-->
          <% if @results.any? %>
	          <% @results.each do |question| %>
		          <div class="card mb-3 rounded shadow-sm alert-info " style=" border-left: 5px solid #5c96b8 ;">
		            <div class="card-title text-dark ">
		              <div class="card-body" >
		              	<strong>
		              	<i>
		              	<%= link_to("#{question.title.to_s} (Posted by: #{question.name.to_s}, Year: #{question.student_year.to_s})", question_path(question), :class => "text-dark") %>
		              	</i>
		              	</strong>
		              </div>
		            </div>
		          </div> 
	          <% end %>
          <% else %>
          	<p class="text-dark">Sorry no search result for your query</p>
          <% end %>
          <!-- INNER  CARD WITH GREEN BG ENDED-->


        </div>


      </div>
    </div><!-- OUTER CARD WITH GREEN BORDER  ENDED-->
  </div><!-- ANSWERS CONTAINER ENDED -->