config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/question/search', to: 'search#index'
  get '/home/dashboard', to: 'dashboard#index'
  get '/notifications', to: 'notification#index'

  resources :questions, only: [:show, :create] do 
    resources :answers, only: [:create]
  end

  # Students routes
	  get '/students/sign_up', to: 'students#get_sign_up'
	  get '/students/sign_in', to: 'students#get_sign_in'
  	post '/students/sign_up', to: 'students#post_sign_up'
  	post '/students/sign_in', to: 'students#post_sign_in'
    delete '/students/sign_out', to: 'students#sign_out'

  # Teachers routes
	  get '/teachers/sign_up', to: 'teachers#get_sign_up'
	  get '/teachers/sign_in', to: 'teachers#get_sign_in'
	  post '/teachers/sign_up', to: 'teachers#post_sign_up'
	  post '/teachers/sign_in', to: 'teachers#post_sign_in'
    delete '/teachers/sign_out', to: 'teachers#sign_out'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dashboard
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<body class="text-center" data-gr-c-s-loaded="true" style=" background: url('https://images.unsplash.com/photo-1478147427282-58a87a120781?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80');
  background-repeat: no-repeat;
  background-size: cover;
  background-position:center;
  ">

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner ">
      <h3 class="cover text-white" style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;" >Query Desk</h3>
    </div>
  </header>
    
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

  
    <!-- Button trigger modal -->
<% if session[:student_user_id] or session[:teacher_user_id] %>
<main role="main" class="inner cover text-white">
    <h1 class="cover-heading">Any Information</h1>
    <p class="lead">Descriptin of the website in a few words or any rules that needs to be specified..</p>
    <%= button_to("Go To Dashboard", home_dashboard_path, :class => "btn btn-lg btn-primary lead", method: :get) %>
</main>
	  <footer class="mastfoot mt-auto">
	    <div class="inner">
	    </div>
	  </footer>
</div>

<% else %>

    <main role="main" class="inner cover text-white">
    <h1 class="cover-heading">Any Information</h1>
    <p class="lead">Descriptin of the website in a few words or any rules that needs to be specified..</p>
	<button type="button" class="btn btn-lg btn-primary lead" data-toggle="modal" data-target="#exampleModalCenter">
	  Let's Start
	</button>

	<!-- Modal -->
	<div class="modal fades" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content ">
	      <div class="modal-header">
	        <h5 class="modal-title text-dark" id="exampleModalLongTitle">Login as</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>

	      <!--First Inner Modal-->
	      <div class="modal-body">
	        <button type="button" class="btn btn-info"
	        data-toggle="modal" data-target="#staticBackdrop"><a  data-dismiss="modal fades" onclick="modal fade1">Student</a>
	        </button>
	         
	      
	    <div class="modal fade1" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	      <div class="modal-dialog modal-dialog-centered" role="document">
	        <div class="modal-content">
	          <div class="modal-header">
	            <h5 class="modal-title text-dark" id="staticBackdropLabel">Choose any One</h5>
	            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	            <span aria-hidden="true">&times;</span>
	            </button>
	          </div>
	            <div class="modal-body">
	            	<%= button_to("Sign In", students_sign_in_path, :class => "btn btn-info", method: :get) %>
	              	<%= button_to("Sign Up", students_sign_up_path, :class => "btn btn-info", method: :get) %>

	        
	          </div>
	          <div class="modal-footer">
	          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        
	          </div>
	        </div>
	      </div>
	    </div>
	       



	  <!--- Second Inner Modal Button-->
	        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop1" ><a  data-dismiss="modal fades" onclick="modal fade2">Teacher</a>
	         </button>
	    
	    <!--- Second Inner Modal starts-->
	        <div class="modal fade2" id="staticBackdrop1" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h5 class="modal-title text-dark" id="staticBackdropLabel">Choose any One</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	         <%= button_to("Sign In", teachers_sign_in_path, :class => "btn btn-info", method: :get) %>
			 <%= button_to("Sign Up", teachers_sign_up_path, :class => "btn btn-info", method: :get) %>
	      </div>
	          <div class="modal-footer">
	          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        
	           </div>
	      </div>
	    </div>
	  </div>




	</div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        
	      </div>
	    </div>
	  </div>
	</div>
	  </main>



	  <footer class="mastfoot mt-auto">
	    <div class="inner">
	     
	    </div>
	  </footer>
	</div>
<% end %>